name: dart_api_project
description: A Dart project with API key management
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dotenv: ^4.1.0
  http: ^1.1.0
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  intl: ^0.19.0

dev_dependencies:
  test: ^1.24.0
